name: Laravel Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, mysql
      - name: Install dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist
      - name: Run migrations
        run: php artisan migrate --force
